version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local

  react:
    image: nginx-proxy_react
    environment:
      - VIRTUAL_HOST=react.local
      - VIRTUAL_PORT=3000
    ports:
      - "3000:3000"

  vue:
    image: reidjs/vue-vuex
    environment:
      - VIRTUAL_HOST=vue.local
      - VIRTUAL_PORT=3001
    ports:
      - "3001:3001"
